'use client';

import React, { useState } from 'react';
import { resolveAlertAction } from '@/app/actions/clinical';
import { ShieldAlert, Check, CheckCircle2, MessageSquare } from 'lucide-react';

interface AlertItem {
  id: string;
  type: string;
  message: string;
  severity: string;
  createdAt: string;
}

interface ClinicalAlertResolverProps {
  alerts: AlertItem[];
}

export default function ClinicalAlertResolver({ alerts }: ClinicalAlertResolverProps) {
  const [resolutionNotes, setResolutionNotes] = useState('');
  const [activeAlertId, setActiveAlertId] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleResolve = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!activeAlertId || !resolutionNotes.trim()) return;

    setLoading(true);
    setError(null);

    const formData = new FormData();
    formData.append('alertId', activeAlertId);
    formData.append('resolutionNotes', resolutionNotes);

    const res = await resolveAlertAction(null, formData);
    setLoading(false);

    if (res.error) {
      setError(res.error);
    } else {
      setResolutionNotes('');
      setActiveAlertId(null);
    }
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-6">
      <div className="border-b border-slate-800 pb-4">
        <h3 className="text-sm font-bold text-white flex items-center gap-2">
          <ShieldAlert className="h-4.5 w-4.5 text-rose-500" />
          Active Telemetry Alerts
        </h3>
        <p className="text-xs text-slate-400 mt-1">Review and acknowledge abnormal vital warnings generated by the Alert Engine.</p>
      </div>

      {alerts.length === 0 ? (
        <div className="p-6 text-center bg-slate-950/40 border border-slate-950 rounded-xl">
          <CheckCircle2 className="h-8 w-8 text-emerald-500 mx-auto mb-2" />
          <p className="text-xs text-slate-400">All alert triggers resolved. Vitals compliance stable.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {alerts.map((alert) => (
            <div
              key={alert.id}
              className={`p-4 rounded-xl border transition-all ${
                activeAlertId === alert.id
                  ? 'bg-slate-950 border-rose-500/50'
                  : 'bg-slate-950/50 border-slate-900 hover:border-slate-850'
              }`}
            >
              <div className="flex justify-between items-start gap-4">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className={`text-[9px] px-1.5 py-0.5 rounded font-bold uppercase ${
                      alert.severity === 'CRITICAL' ? 'bg-rose-500/10 text-rose-400 border border-rose-500/20' :
                      'bg-amber-500/10 text-amber-400 border border-amber-500/20'
                    }`}>
                      {alert.severity}
                    </span>
                    <span className="text-[10px] text-slate-500">
                      Logged: {new Date(alert.createdAt).toLocaleString()}
                    </span>
                  </div>
                  <p className="text-xs text-slate-200 font-medium leading-relaxed pt-1">
                    {alert.message}
                  </p>
                </div>

                {activeAlertId !== alert.id && (
                  <button
                    onClick={() => setActiveAlertId(alert.id)}
                    className="px-2.5 py-1 rounded bg-rose-500/10 text-rose-400 border border-rose-500/20 hover:bg-rose-500 hover:text-slate-950 transition-all text-[10px] font-bold shrink-0"
                  >
                    Resolve Alert
                  </button>
                )}
              </div>

              {/* Form expansion */}
              {activeAlertId === alert.id && (
                <form onSubmit={handleResolve} className="mt-4 pt-4 border-t border-slate-900 space-y-3">
                  {error && (
                    <div className="p-2 rounded bg-rose-950/30 border border-rose-900/50 text-rose-400 text-[10px]">
                      {error}
                    </div>
                  )}
                  <div>
                    <label className="block text-[9px] uppercase font-bold text-slate-500 tracking-wider mb-1">
                      Clinical Action Notes
                    </label>
                    <textarea
                      required
                      placeholder="e.g. Advised patient to adjust Amlodipine dosage and rest. Follow-up logged."
                      rows={2}
                      value={resolutionNotes}
                      onChange={(e) => setResolutionNotes(e.target.value)}
                      className="w-full px-3 py-2 rounded-lg bg-slate-900 border border-slate-800 focus:border-rose-500 text-xs text-white placeholder-slate-700 outline-none resize-none"
                    />
                  </div>
                  <div className="flex gap-2 justify-end">
                    <button
                      type="button"
                      onClick={() => setActiveAlertId(null)}
                      className="px-2.5 py-1 rounded bg-slate-900 hover:bg-slate-850 text-slate-400 border border-slate-800 text-[10px] font-bold"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      disabled={loading}
                      className="px-3 py-1 rounded bg-rose-500 hover:bg-rose-400 text-slate-950 text-[10px] font-bold flex items-center gap-1 transition-all disabled:opacity-50"
                    >
                      <Check className="h-3 w-3" />
                      {loading ? 'Submitting...' : 'Confirm Resolution'}
                    </button>
                  </div>
                </form>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
